services:
  memgraph-platform:
    image: "memgraph/memgraph-platform:2.10.2-memgraph2.10.1-lab2.8.1-mage1.10"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH="--log-level=INFO"
    entrypoint: ["/usr/bin/supervisord"]
    networks:
      - memnet

volumes:
  mg_lib:
  mg_log:
  mg_etc:

networks:
  memnet:
